[package]
edition = "2021"
name = "riscv-mem"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "riscv_mem"
path = "src/lib.rs"

[dependencies]
bitflags = "2"
riscv = "0.10"
